""" Physical/numerical constants """
ST_GRAVITY = 9.81
KINEMATIC_VISCOSITY = 1.004e-6
DW_HEAD_TOLERANCE = 1e-3
DW_VELOCITY_TOLERANCE = 1e-5
DW_ROUGHNESS_EPSILON = 1e-6
DW_COEFF_MAX = 0.08
DW_COEFF_DEFAULT = 0.01
